<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>VerityWorkbench.Media</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\VerityWorkbench.Core\VerityWorkbench.Core.csproj" />
  </ItemGroup>
</Project>
